import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth0 } from '@auth0/auth0-react';

const Login = () => {
  const navigate = useNavigate();
  const { loginWithRedirect } = useAuth0();
  const [formData, setFormData] = useState({
    username: '',
    password: '',
  });
  const [isLoading, setIsLoading] = useState(false);
  const [focusedInput, setFocusedInput] = useState(null);

  useEffect(() => {
    // Check for tokens in URL (from backend redirect after Google login)
    const params = new URLSearchParams(window.location.search);
    const token = params.get('token');
    const userStr = params.get('user');

    if (token && userStr) {
      try {
        const user = JSON.parse(decodeURIComponent(userStr));
        localStorage.setItem('authToken', token);
        localStorage.setItem('user', JSON.stringify(user));
        console.log('✅ Login successful:', user.name);
        // Navigate to home page
        navigate('/', { replace: true });
      } catch (error) {
        console.error('Failed to parse user data:', error);
      }
    }
  }, [navigate]);


  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      const response = await fetch('http://localhost:5000/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify(formData)
      });

      const data = await response.json();

      if (response.ok) {
        localStorage.setItem('authToken', data.token);
        localStorage.setItem('user', JSON.stringify(data.user));
        navigate('/');
      } else {
        alert(data.error || 'Login failed');
      }
    } catch (error) {
      console.error('Login error:', error);
      alert('Login failed. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGoogleLogin = () => {
    // Redirect to backend auth route to initiate server-side flow
    // This ensures we get the custom authToken generated by our backend
    const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';
    window.location.href = `${API_URL}/api/auth/auth0-login`;
  };

  return (
    <div className="min-h-screen w-full flex items-center justify-center bg-[#0A0A0B] p-4 relative overflow-hidden">
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40vw] h-[40vw] bg-[#7000FF]/20 rounded-full blur-[120px] animate-pulse"></div>
        <div className="absolute bottom-[-10%] right-[-10%] w-[40vw] h-[40vw] bg-[#00D1FF]/10 rounded-full blur-[120px] animate-pulse delay-1000"></div>
        <div className="absolute top-[20%] right-[20%] w-[20vw] h-[20vw] bg-purple-500/10 rounded-full blur-[100px] animate-blob"></div>
      </div>

      <div className="relative w-full max-w-5xl mx-auto flex flex-col-reverse lg:flex-row rounded-3xl overflow-hidden shadow-2xl shadow-[#7000FF]/10 backdrop-blur-xl border border-white/10 z-10 bg-[#0A0A0B]/60">

        <div className="w-full lg:w-1/2 p-8 md:p-12 lg:p-16 flex flex-col justify-center relative z-20">
          <div className="mb-8">
            <h2 className="text-4xl font-black text-white mb-2 tracking-tight">
              Welcome <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#00D1FF] to-[#7000FF]">Back</span>
            </h2>
            <p className="text-gray-400">Resume your roadmap journey.</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="group relative">
              <label
                className={`absolute left-4 transition-all duration-300 pointer-events-none ${focusedInput === 'username' || formData.username ? '-top-2.5 text-xs text-[#00D1FF] bg-[#0A0A0B] px-2' : 'top-3.5 text-gray-500'
                  }`}
              >
                Username or Email
              </label>
              <input
                type="text"
                name="username"
                value={formData.username}
                onChange={handleChange}
                onFocus={() => setFocusedInput('username')}
                onBlur={() => setFocusedInput(null)}
                className="w-full bg-[#1A1A1E] border border-gray-800 rounded-xl px-4 py-3.5 text-white outline-none focus:border-[#00D1FF] focus:shadow-[0_0_20px_rgba(0,209,255,0.3)] transition-all duration-300"
                required
              />
            </div>

            <div className="group relative">
              <label
                className={`absolute left-4 transition-all duration-300 pointer-events-none ${focusedInput === 'password' || formData.password ? '-top-2.5 text-xs text-[#7000FF] bg-[#0A0A0B] px-2' : 'top-3.5 text-gray-500'
                  }`}
              >
                Password
              </label>
              <input
                type="password"
                name="password"
                value={formData.password}
                onChange={handleChange}
                onFocus={() => setFocusedInput('password')}
                onBlur={() => setFocusedInput(null)}
                className="w-full bg-[#1A1A1E] border border-gray-800 rounded-xl px-4 py-3.5 text-white outline-none focus:border-[#7000FF] focus:shadow-[0_0_20px_rgba(112,0,255,0.3)] transition-all duration-300"
                required
              />
            </div>

            <div className="flex items-center justify-end">
              <button
                type="button"
                onClick={() => alert("Coming soon!")}
                className="text-sm text-gray-400 hover:text-[#00D1FF] transition-colors"
              >
                Forgot Password?
              </button>
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-4 bg-gradient-to-r from-[#7000FF] to-[#00D1FF] text-white font-bold rounded-xl hover:shadow-[0_0_40px_rgba(112,0,255,0.5)] hover:scale-[1.02] active:scale-[0.98] transition-all duration-300 relative overflow-hidden group"
            >
              <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
              <span className="relative flex items-center justify-center gap-2">
                {isLoading ? 'Accessing Neural Link...' : 'Login Now'}
                {!isLoading && (
                  <svg className="w-5 h-5 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14 5l7 7m0 0l-7 7m7-7H3" /></svg>
                )}
              </span>
            </button>
          </form>

          <div className="my-8 flex items-center gap-4">
            <div className="h-px bg-gray-800 flex-1"></div>
            <span className="text-gray-500 text-sm">OR CONTINUE WITH</span>
            <div className="h-px bg-gray-800 flex-1"></div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <button
              onClick={handleGoogleLogin}
              className="flex items-center justify-center gap-2 py-3 bg-[#1A1A1E] border border-gray-800 rounded-xl hover:bg-[#25252A] hover:border-gray-700 transition-all duration-300 group"
            >
              <svg className="w-5 h-5 group-hover:scale-110 transition-transform duration-300" viewBox="0 0 24 24">
                <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
              </svg>
              <span className="text-gray-300 font-medium">Google</span>
            </button>
            <button
              onClick={() => alert("Coming soon!")}
              className="flex items-center justify-center gap-2 py-3 bg-[#1A1A1E] border border-gray-800 rounded-xl hover:bg-[#25252A] hover:border-gray-700 transition-all duration-300 group"
            >
              <svg className="w-5 h-5 text-[#1877F2] group-hover:scale-110 transition-transform duration-300" fill="currentColor" viewBox="0 0 24 24">
                <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z" />
              </svg>
              <span className="text-gray-300 font-medium">Facebook</span>
            </button>
          </div>

          <p className="mt-8 text-center text-gray-400">
            First time here?{' '}
            <Link to="/register" className="text-[#00D1FF] hover:text-[#7000FF] font-semibold transition-colors">
              Create Account
            </Link>
          </p>
        </div>

        <div className="hidden lg:flex w-full lg:w-1/2 bg-[#0F0F12] relative overflow-hidden items-center justify-center p-10 min-h-[400px] lg:min-h-auto border-l border-white/5">
          <div className="relative w-64 h-64 md:w-96 md:h-96">
            <svg className="w-full h-full drop-shadow-[0_0_30px_rgba(112,0,255,0.3)]" viewBox="0 0 200 200">
              <defs>
                <radialGradient id="grad1" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
                  <stop offset="0%" style={{ stopColor: '#7000FF', stopOpacity: 0.6 }} />
                  <stop offset="100%" style={{ stopColor: '#00D1FF', stopOpacity: 0 }} />
                </radialGradient>
              </defs>

              <circle cx="100" cy="100" r="40" fill="url(#grad1)" className="animate-pulse" />

              <g stroke="rgba(255,255,255,0.1)" strokeWidth="0.5">
                <path d="M100,60 Q130,30 160,60" fill="none" className="animate-[pulse_4s_infinite]" />
                <path d="M100,140 Q70,170 40,140" fill="none" className="animate-[pulse_4s_infinite_1s]" />
                <path d="M60,100 Q30,70 60,40" fill="none" className="animate-[pulse_4s_infinite_2s]" />
                <path d="M140,100 Q170,130 140,160" fill="none" className="animate-[pulse_4s_infinite_0.5s]" />
              </g>

              <g className="animate-[spin_20s_linear_infinite] origin-center">
                <circle cx="100" cy="40" r="3" fill="#00D1FF">
                  <animate attributeName="r" values="3;5;3" dur="2s" repeatCount="indefinite" />
                </circle>
                <circle cx="160" cy="100" r="2" fill="#7000FF" opacity="0.8" />
                <circle cx="100" cy="160" r="3" fill="#00D1FF">
                  <animate attributeName="r" values="3;4;3" dur="3s" repeatCount="indefinite" />
                </circle>
                <circle cx="40" cy="100" r="2" fill="#7000FF" opacity="0.8" />

                <line x1="100" y1="40" x2="160" y2="100" stroke="#00D1FF" strokeWidth="0.5" opacity="0.3" />
                <line x1="160" y1="100" x2="100" y2="160" stroke="#7000FF" strokeWidth="0.5" opacity="0.3" />
                <line x1="100" y1="160" x2="40" y2="100" stroke="#00D1FF" strokeWidth="0.5" opacity="0.3" />
                <line x1="40" y1="100" x2="100" y2="40" stroke="#7000FF" strokeWidth="0.5" opacity="0.3" />
              </g>

              <g className="animate-[spin_15s_linear_infinite_reverse] origin-center">
                <circle cx="142" cy="58" r="2" fill="#fff" opacity="0.6" />
                <circle cx="58" cy="142" r="2" fill="#fff" opacity="0.6" />
              </g>

            </svg>

            <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#00D1FF]/10 to-transparent h-4 w-full animate-[scan_3s_linear_infinite]"></div>

            <div className="absolute -bottom-10 left-0 right-0 text-center">
              <p className="text-white/80 font-mono text-sm tracking-[0.2em] animate-pulse">NEURAL LINK ACTIVE</p>
              <p className="text-[#00D1FF] text-xs mt-1">ACCESSING DATABASE</p>
            </div>
          </div>

          <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_50%,#000_70%,transparent_100%)] pointer-events-none"></div>
        </div>
      </div>

      <style>{`
        @keyframes scan {
            0% { top: 0%; opacity: 0; }
            50% { opacity: 1; }
            100% { top: 100%; opacity: 0; }
        }
      `}</style>
    </div>
  );
};

export default Login;
